#Inquisitor G1V0.2

import logging, os

safe    = """Safe"""
Creator = """MoraByte2027"""

class malicious(object):
    Critical    = """Critically Sinister and Malevolent"""
    NonCritical = """NonCritical but Malicious"""

def _Choice(Msg: str = None):
    print(Msg)
    choice = input("Yes/No(Yes or No): ")
    choice = choice.replace('Y', '10')
    choice = choice.replace('y', '10')
    choice = choice.replace('E', '0')
    choice = choice.replace('S', '1')
    choice = choice.replace('e', '0')
    choice = choice.replace('s', '1')
    choice = choice.replace('N', '01')
    choice = choice.replace('n', '01')
    choice = choice.replace('O', '11')
    choice = choice.replace('o', '11')
    if choice=="1001": choice = True
    elif choice=="0111": choice = False

def cscan(content):
    detection = ""
    Score = 0

    x = (content.find('Rar! '))
    if x > -1: detection += '@' + ('RarPacked')
    if x > -1: Score = Score + 3
    x = (content.find("7zÂ¼Â¯' "))
    if x > -1: detection += '@' + ('7zPacked')
    if x > -1: Score = Score + 3
    x = (content.find('æŒ¦ç ¬à¨ '))
    if x > -1: detection += '@' + ('Obfuscated')
    if x > -1: Score = Score + 3
    x = (content.find(':BFP'))
    if x > -1: detection += '@' + ('Obfuscated')
    if x > -1: Score = Score + 4
    x = (content.find('hatsploit'))
    if x > -1: detection += '@' + ('Hatsploit')
    if x > -1: Score = Score + 3
    x = (content.find('net user \%username%'))
    if x > -1: detection += '@' + ('NetPassword')
    if x > -1: Score = Score + 16
    x = (content.find('net1 user \%username%'))
    if x > -1: detection += '@' + ('NetPassword')
    if x > -1: Score = Score + 16
    x = (content.find('net share'))
    if x > -1: detection += '@' + ('NetShare')
    if x > -1: Score = Score + 7
    x = (content.find('net1 share'))
    if x > -1: detection += '@' + ('NetShare')
    if x > -1: Score = Score + 7
    x = (content.find('%COMSPEC% /C start %COMSPEC% /C \\WINDOWS\\Temp'))
    if x > -1: Score = Score + 3
    x = (content.find('bash -c \'exec bash -i &>/dev/tcp/'))
    if x > -1: detection += '@' + ('Bash')
    if x > -1: Score = Score + 3
    x = (content.find('zsh -c \'zmodload zsh/net/tcp && ztcp'))
    if x > -1: detection += '@' + ('Zsh')
    if x > -1: Score = Score + 3
    x = (content.find('zsh >&$REPLY 2>&$REPLY 0>&$REPLY\''))
    if x > -1: detection += '@' + ('Zsh')
    if x > -1: Score = Score + 3
    x = (content.find('rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc'))
    if x > -1: detection += '@' + ('NCat')
    if x > -1: Score = Score + 3
    x = (content.find('TF=$(mktemp -u); mkfifo $TF && telnet'))
    if x > -1: detection += '@' + ('telnet')
    if x > -1: Score = Score + 3
    x = (content.find('0<$TF | /bin sh 1>$TF'))
    if x > -1: Score = Score + 3
    x = (content.find('bash -c \'echo -e "POST / HTTP/0.9 $(<'))
    if x > -1: detection += '@' + ('BashHttp')
    if x > -1: Score = Score + 3
    x = (content.find('> /dev/tcp/'))
    if x > -1: detection += '@' + ('BashTCP')
    if x > -1: Score = Score + 3
    x = (content.find('D$UPPPj'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 19
    x = (content.find('D$Ej'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 19
    x = (content.find('|$JQu0'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 19
    x = (content.find('D$CjNh'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 19
    x = (content.find('|$BQun'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 19
    x = (content.find('taskhcst'))
    if x > -1: detection += '@' + ('wannacry')
    if x > -1: Score = Score + 19
    x = (content.find('lsasvs'))
    if x > -1: detection += '@' + ('wannacry')
    if x > -1: Score = Score + 19
    x = (content.find('cscc'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    if x > -1: Score = Score + 19
    x = (content.find('infpub'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    if x > -1: Score = Score + 19
    x = (content.find('perfc'))
    if x > -1: detection += '@' + ('Petya')
    if x > -1: Score = Score + 19
    x = (content.find('taskkill'))
    if x > -1: detection += '@' + ('taskkill')
    if x > -1: Score = Score + 3
    x = (content.find('pskill'))
    if x > -1: detection += '@' + ('taskkill')
    if x > -1: Score = Score + 3
    x = (content.find('pskill64'))
    if x > -1: detection += '@' + ('taskkill')
    if x > -1: Score = Score + 3
    x = (content.find('tskill'))
    if x > -1: detection += '@' + ('taskkill')
    if x > -1: Score = Score + 3
    x = (content.find('C:\\Windows'))
    if x > -1: detection += '@' + ('SystemTamper')
    if x > -1: Score = Score + 3
    x = (content.find('C:\\Windows\\System32'))
    if x > -1: detection += '@' + ('SystemTamper')
    if x > -1: Score = Score + 1
    x = (content.find('csrss'))
    if x > -1: detection += '@' + ('SystemTamper')
    if x > -1: Score = Score + 4
    x = (content.find('wininit'))
    if x > -1: detection += '@' + ('SystemTamper')
    if x > -1: Score = Score + 4
    x = (content.find('svchost'))
    if x > -1: detection += '@' + ('ServiceTamper')
    if x > -1: Score = Score + 4
    x = (content.find('msmpeng'))
    if x > -1: detection += '@' + ('ProtectionTamper')
    if x > -1: Score = Score + 4
    x = (content.find('ntoskrnl'))
    if x > -1: detection += '@' + ('KernelTamper')
    if x > -1: Score = Score + 4
    x = (content.find('winlogon'))
    if x > -1: detection += '@' + ('LoginTamper')
    if x > -1: Score = Score + 4
    x = (content.find('socket.socket(socket.AF_INET'))
    if x > -1: detection += '@' + ('PYSocket')
    if x > -1: Score = Score + 3
    x = (content.find('wscript.exe /b /nologo /E:javascript'))
    if x > -1: detection += '@' + ('vbsjs')
    if x > -1: Score = Score + 3
    x = (content.find('Invoke-Mimikatz'))
    if x > -1: detection += '@' + ('Mimikatz')
    if x > -1: Score = Score + 21
    x = (content.find('copy \%%.*0'))
    if x > -1: detection += '@' + ('Copyself')
    if x > -1: Score = Score + 3
    x = (content.find('cacls'))
    if x > -1: detection += '@' + ('PermissionTamper')
    if x > -1: Score = Score + 4
    x = (content.find('takeown'))
    if x > -1: detection += '@' + ('PermissionTamper')
    if x > -1: Score = Score + 4
    x = (content.find('RMDIR'))
    if x > -1: detection += '@' + ('Deleter')
    if x > -1: Score = Score + 3
    x = (content.find('REPLACE'))
    if x > -1: detection += '@' + ('Replace')
    if x > -1: Score = Score + 3
    x = (content.find('ASSOC'))
    if x > -1: detection += '@' + ('assoc')
    if x > -1: Score = Score + 2
    x = (content.find('ATTRIB'))
    if x > -1: detection += '@' + ('Attributes')
    if x > -1: Score = Score + 3
    x = (content.find('FSUTIL'))
    if x > -1: detection += '@' + ('fsutil')
    if x > -1: Score = Score + 8
    x = (content.find('WMIC'))
    if x > -1: detection += '@' + ('wmic')
    if x > -1: Score = Score + 5
    x = (content.find('wbadmin'))
    if x > -1: detection += '@' + ('BackupTamper')
    if x > -1: Score = Score + 16
    x = (content.find('vssadmin'))
    if x > -1: detection += '@' + ('ShadowcopyTamper')
    if x > -1: Score = Score + 16
    x = (content.find('wmic shadowcopy'))
    if x > -1: detection += '@' + ('ShadowcopyTamper')
    if x > -1: Score = Score + 11
    x = (content.find('bcdedit'))
    if x > -1: detection += '@' + ('BootEdit')
    if x > -1: Score = Score + 16
    x = (content.find('bcdedit /delete'))
    if x > -1: detection += '@' + ('BootDel')
    if x > -1: Score = Score + 68
    x = (content.find('bcdedit/delete'))
    if x > -1: detection += '@' + ('BootDel')
    if x > -1: Score = Score + 68
    x = (content.find('php -r \'$sock=fsockopen(getenv('))
    if x > -1: detection += '@' + ('PhpSock')
    if x > -1: Score = Score + 3
    x = (content.find('powershell -nop -c "$client = New-Object System.Net.Sockets.TCPClient(\''))
    if x > -1: detection += '@' + ('PSSocket')
    if x > -1: Score = Score + 3
    x = (content.find('python -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect'))
    if x > -1: detection += '@' + ('PYSocket')
    if x > -1: Score = Score + 3
    x = (content.find('ruby -rsocket -e \\\'exit if fork;c=TCPSocket.new(ENV['))
    if x > -1: detection += '@' + ('RubyRSocket')
    if x > -1: Score = Score + 3
    x = (content.find('bash -c \'cat'))
    if x > -1: detection += '@' + ('BashCat')
    if x > -1: Score = Score + 3
    x = (content.find('nc -l -p'))
    if x > -1: detection += '@' + ('NCat')
    if x > -1: Score = Score + 1
    x = (content.find('nc -lnvp ;'))
    if x > -1: detection += '@' + ('NCat')
    if x > -1: Score = Score + 1
    x = (content.find('python3 -m http.server'))
    if x > -1: detection += '@' + ('PYHttp')
    if x > -1: Score = Score + 4
    x = (content.find('python -m SimpleHTTPServer'))
    if x > -1: detection += '@' + ('PYHttp')
    if x > -1: Score = Score + 4
    x = (content.find('scp pl'))
    if x > -1: detection += '@' + ('SCP')
    if x > -1: Score = Score + 4
    x = (content.find(':~/destination -P'))
    if x > -1: Score = Score + 3
    x = (content.find('scp user@'))
    if x > -1: detection += '@' + ('SCP')
    if x > -1: Score = Score + 4
    x = (content.find(':~/path_to_file file_saved -P'))
    if x > -1: detection += '@' + ('datpath')
    if x > -1: Score = Score + 5
    x = (content.find('document.cookie'))
    if x > -1: detection += '@' + ('HTCookie')
    if x > -1: Score = Score + 3
    x = (content.find('getItem(\'access_token\')'))
    if x > -1: detection += '@' + ('HTCookie')
    if x > -1: Score = Score + 3
    x = (content.find('UNION SELECT NULL,NULL,NULL'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION ORDER BY 1'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION SELECT @@version'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION SELECT banner from v$version'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION SELECT version'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION SELECT table_name,NULL from INFORMATION_SCHEMA.TABLES'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('UNION SELECT table_name,NULL FROM all_tables'))
    if x > -1: detection += '@' + ('SQL')
    if x > -1: Score = Score + 7
    x = (content.find('System.Windows.Forms'))
    if x > -1: detection += '@' + ('WindowsForms')
    if x > -1: Score = Score + 7
    x = (content.find('PopUp'))
    if x > -1: detection += '@' + ('Popup')
    if x > -1: Score = Score + 3
    x = (content.find('[\\w-]\{24}\\.[\\w-]\{6}\\.[\\w-]\{27}" /c:"mfa\\.[\\w-]\{84}'))
    if x > -1: detection += '@' + ('Other')
    if x > -1: Score = Score + 21
    x = (content.find('hcrypt'))
    if x > -1: detection += '@' + ('Hcrypt')
    if x > -1: Score = Score + 7
    x = (content.find('/remove *S-1-5-32-544 *S-1-5-11 *S-1-5-32-545 *S-1-5-18'))
    if x > -1: Score = Score + 8
    x = (content.find('ConsentPromptBehaviorAdmin'))
    if x > -1: detection += '@' + ('UACAdminConsentPromptTamper')
    if x > -1: Score = Score + 8
    x = (content.find('HKLM\\Software\\Policies\\Microsoft\\Windows Defender\\UX Configuration'))
    if x > -1: detection += '@' + ('ProtectionTamper')
    if x > -1: Score = Score + 8
    x = (content.find('Notification_Suppress'))
    if x > -1: detection += '@' + ('NotificationSuppresser')
    if x > -1: Score = Score + 8
    x = (content.find('DisableTaskMgr'))
    if x > -1: detection += '@' + ('DisableTaskManager')
    if x > -1: Score = Score + 7
    x = (content.find('DisableCMD'))
    if x > -1: detection += '@' + ('DisableCommandline')
    if x > -1: Score = Score + 7
    x = (content.find('DisableRegistryTools'))
    if x > -1: detection += '@' + ('DisableRegistryTools')
    if x > -1: Score = Score + 7
    x = (content.find('HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies'))
    if x > -1: detection += '@' + ('PoliciesTamper')
    if x > -1: Score = Score + 8
    x = (content.find('NoRun'))
    if x > -1: detection += '@' + ('NoRun')
    if x > -1: Score = Score + 1
    x = (content.find('windefend'))
    if x > -1: detection += '@' + ('ProtectionTamper')
    if x > -1: Score = Score + 8
    x = (content.find('Add-MpPreference'))
    if x > -1: detection += '@' + ('ProtectionTamper')
    if x > -1: Score = Score + 8
    x = (content.find('Start Menu\\Programs\\Startup'))
    if x > -1: detection += '@' + ('Startup')
    if x > -1: Score = Score + 7
    x = (content.find('advfirewall'))
    if x > -1: detection += '@' + ('Firewall')
    if x > -1: Score = Score + 7
    x = (content.find('//4mY2xzDQo='))
    if x > -1: detection += '@' + ('CanObfuscate')
    if x > -1: Score = Score + 4
    x = (content.find('certutil'))
    if x > -1: detection += '@' + ('Certutil')
    if x > -1: Score = Score + 2
    x = (content.find('JKbtgdfd'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('510501002024'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GentProcessID@0'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_ResumePhrocess@4'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GetThureadList@12'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_SutspendProcess@4'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GetPrkrocessList@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GetPronhcessName@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GetThrehjadContext@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_ReadRehmoteMemory@16'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_WriteRehmoteMemory@16'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_AllocahteRemoteMemory@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_GejtModuleBaseAddress@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_TerminatejbProcessByID@4'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('_CheckPirocessForString@8'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find('BACAIHJHUTVTWT[Zbadcecfcgchciclkrqsq}|~|'))
    if x > -1: detection += '@' + ('Agent Tesla')
    if x > -1: Score = Score + 8
    x = (content.find('3/9;h~lo/0jcdibnch-~~l]1'))
    if x > -1: detection += '@' + ('Agent Tesla')
    if x > -1: Score = Score + 8
    x = (content.find(' / a n'))
    if x > -1: detection += '@' + ('Ursnif')
    if x > -1: Score = Score + 7
    x = (content.find('ngTinC'))
    if x > -1: detection += '@' + ('Formbook')
    if x > -1: Score = Score + 4
    x = (content.find('adminToolStripMenuItem_Click'))
    if x > -1: detection += '@' + ('Formbook')
    if x > -1: Score = Score + 4
    x = (content.find('ngaySinh'))
    if x > -1: detection += '@' + ('Formbook')
    if x > -1: Score = Score + 4
    x = (content.find('soDienThoai'))
    if x > -1: detection += '@' + ('Formbook')
    if x > -1: Score = Score + 4
    x = (content.find('btn_Update_Click'))
    if x > -1: detection += '@' + ('Generic Malware')
    if x > -1: Score = Score + 4
    x = (content.find(')>-;8*#'))
    if x > -1: detection += '@' + ('Agent Tesla')
    if x > -1: Score = Score + 8
    x = (content.find('hycdhyl{d'))
    if x > -1: detection += '@' + ('Agent Tesla')
    if x > -1: Score = Score + 8
    x = (content.find('8SVWjnXjtf'))
    if x > -1: detection += '@' + ('Formbook')
    if x > -1: Score = Score + 4
    x = (content.find('encryptionAesRsa'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkStartupFolder'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkdeleteBackupCatalog'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutexStartup2'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutexStartup'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('surprise.exe'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('(?:[13]\{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|bc1[a-z0-9]{39,59})'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkdisableRecoveryMode'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkdeleteShadowCopies'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('7z459ajrk722yn8c5j4fg'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('sleepOutOfTempFolder'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('1qw0ll8p9m8uezhqhyd'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('2X28tfRmWaPyPQgvoHV'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('copyResistForAdmin'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkCopyRoaming'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('17CqMQFeuB3NTzJ'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('addAndOpenNote'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutexRegex'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('sleepTextbox'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutexRun2'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('randomEncode'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('checkSpread'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('copyRoaming'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutexRun'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('spreadName'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('appMutex2'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('spreadIt'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('addLinkToStartup'))
    if x > -1: detection += '@' + ('CHAOS Ransomware')
    if x > -1: Score = Score + 7
    x = (content.find('encrypted_key":"'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('[\%04i/\%02i/\%02i \%02i:\%02i:\%02i'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('0!0-070K0W0e0o0{0'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('606A6G6M6T6a6'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find(';+;=;I;Q;i;'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('L$,#L$ #D$,'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('T$$#T$(#D$$'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('m0~0a2l2|2'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('5<5B5G5M5^5'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('5(5N5f5l5'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('K j@^+s`;'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('u PPj7UPQ'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('C`UVWj@_'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('u:E;l$(|'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('L$ !t$ j'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('t$Pf \\$V'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('W?PPUSPQ'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('\\$(X+D$$'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('[BckSp]'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('Remcos'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('CreateObject("WScript.Shell").Run "cmd /c ""'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('t]<*u?N'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('SUVWj7_'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('pth_unenc'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('StopReverse'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('fso.DeleteFolder "'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('while fso.FileExists("'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('GetDirectListeningPort'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('/sort "Visit Time" /stext "'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('wnd_\%04i\%02i\%02i_\%02i\%02i\%02i'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('time_\%04i\%02i\%02i_\%02i\%02i\%02i'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('fso.DeleteFile(Wscript.ScriptFullName)'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('9l$`~A'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('t$LVU3'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('tD;Ntr'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('VjxVVh'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('L$<jHY'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('s u&j@'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('D$$PuJ'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('u79|$$'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('_9l$Lt'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('SVWjGZ'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find(';G,uBSV'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('t%<.t<G'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('^f9t$ s'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('I9t$4t+'))
    if x > -1: detection += '@' + ('REMCOS')
    if x > -1: Score = Score + 6
    x = (content.find('SYSTEM\\CurrentControlSet\\ControlTerminal Server\\AddIns\\Clip Redirector'))
    if x > -1: detection += '@' + ('AVE_MARIA')
    if x > -1: Score = Score + 5
    x = (content.find('select signon_realm, origin_url, username_value, password_value from wow_logins'))
    if x > -1: detection += '@' + ('AVE_MARIA')
    if x > -1: Score = Score + 5
    x = (content.find('Ave_Maria Stealer OpenSource github Link: https://github.com/syohex/java-simple-mine-sweeper'))
    if x > -1: detection += '@' + ('AVE_MARIA')
    if x > -1: Score = Score + 5
    x = (content.find('A pure virtual function was called. This is a fatal error, and indicates a serious error in the implementation of the application'))
    if x > -1: detection += '@' + ('AVE_MARIA')
    if x > -1: Score = Score + 5
    x = (content.find('cmd.exe /C ping 1.2.3.4 -n 2 -w 1000 > Nul & Del /f /q'))
    if x > -1: detection += '@' + ('AVE_MARIA')
    if x > -1: Score = Score + 5
    x = (content.find('N^RV[\\6yeg'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('jVfc8\\@OeU'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('PqIIi4Zb>4'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('nj)r\\Rx?Jj'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('dt9q9<oDf7'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('8yi"V    Ww|8'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('Ydk{g(B7Hj'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('%\\4*<b"]q2-'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('\%M|+K|K28/,'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('WNPNLNENS.T'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('s\'EtEDW@ts~L'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('51=o>g7RxQj='))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('F* ($,"*&.!)\''))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('_t:lN+XBjRe\' '))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('0\/0?0F0b0s0z0'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('2 282?2K2Z2u2|2'))
    if x > -1: detection += '@' + ('BadRabbit')
    if x > -1: Score = Score + 19
    x = (content.find('*ssfn*'))
    if x > -1: detection += '@' + ('NexusLogger')
    if x > -1: Score = Score + 10
    x = (content.find('i>k__BackingField'))
    if x > -1: detection += '@' + ('Habbo')
    if x > -1: Score = Score + 10
    x = (content.find('BCrbMasterKeyyptImbMasterKeyportKbMasterKeyey'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SELSystem.LinqECT * FRSystem.LinqOM WinSystem.Linq32_VideoCoSystem.Linqntroller'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SSystem.ELECT * FRSystem.OM WiSystem.n32_ProcSystem.ess WherSystem.e SessiSystem.onId=\''))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('\%USERPserviceInterface.ExtensionROFILE\%\\ApserviceInterface.ExtensionpData\\LocaserviceInterface.Extensionl'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('\%USERPserviceInterface.ExtensionROFILE%\\ApserviceInterface.ExtensionpData\\LocaserviceInterface.Extensionl'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SELSystem.Windows.FormsECT * FRSystem.Windows.FormsOM WinSystem.Windows.Forms32_ProcSystem.Windows.Formsessor'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SELESystem.ManagementCT * FRSystem.ManagementOM WiSystem.Managementn32_DisSystem.ManagementkDrivSystem.Managemente'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SELSystem.Text.RegularExpressionsECT * FRSystem.Text.RegularExpressionsOM Win32_PSystem.Text.RegularExpressionsrocess WSystem.Text.RegularExpressionshere SessSystem.Text.RegularExpressionsionId=\''))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('KDBM(6'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('MSObject32'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('*wallet*'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('chromeKey'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('https://api.ip.sb/ip'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('\\Discord\\Local Storage\\leveldb'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<GetWindowsVersion>g__HKLM_GetString|11_0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('nSystem.CollectionspvoSystem.Collections*'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('cFileStreamredFileStreamit_cFileStreamardFileStreams'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('\%USERPFile.WriteROFILE%\\AppFile.WriteData\\RoamiFile.Writeng'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('BCrstring.EmptyyptOpestring.EmptynAlgorithmProvistring.Emptyder'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('SELEMemoryCT * FMemoryROM WiMemoryn32_OperMemoryatingSMemoryystem'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('\\TeEnvironmentlegraEnvironmentm DEnvironmentesktoEnvironmentp\\tdEnvironmentata'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<DomainExists>b__0_0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('GetDefaultIPv4Address'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<ListOfPrograms>b__8_0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('ProldCharotonVoldCharPN'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('serviceInterface.Extension'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<AvailableLanguages>b__9_0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<GetDefaultIPv4Address>b__1_1'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<GetDefaultIPv4Address>b__1_0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('roSystem.Linqot\\CISystem.LinqMV2'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('Concat0 MConcatb oConcatr Concat0'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('BCrUnmanagedTypeyptDecrUnmanagedTypeypt'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('E3E8284EDCB98A1085E693F9525A3AC3D705B82E'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('7FD227EEE2F38A50CFD286D228B794575C0025FB'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('FB10FF1AD09FE8F5CA3A85B06BC96596AF83B350'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('A898408AA9A30B686240D921FE0E3E3A01EE91A5'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('93D9D319FF04F5E54F3A6431407A7B90388FDC54'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('1938FDF81D9EFE09E9786A7A7DDFFBD755961098'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('410D551BF9DC1F0CF262E4DB1077795D56EEC026'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('8C550EA96A693C687FFAB21F3B1A5F835E23E3B3'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('28F794B091ED92F57BFC80EA32B18AF3A8183ADB'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('2A19BFD7333718195216588A698752C517111B02'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('99086C63443EF4224B60D2ED08447C082E7A0484'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('718D1294A5C2D3F3D70E09F2F473155C4F567201'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('1A79939AEFF161E557D02CB37CD9A811ABCAF458'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('6353B688B99A3543932AA127DAA0E48FBC646BBD'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('scannerArg'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('GatherValue'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('browserPaths'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('String.Remove'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('ChromeGetName'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('FileStream.IO'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('String.Replace'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('string.Replace'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('FileScannerRule'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('IRemoteEndpoint'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('ReadContextValue'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('ReadContextTable'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<DomainExists>b__2'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('ReadMasterOfContext'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('<DomainExists>b__0_1'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('NordVpn.exe*MyGToMyGkens.tMyGxt'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('NoGetDirectoriesrd'))
    if x > -1: detection += '@' + ('RedLine stealer')
    if x > -1: Score = Score + 4
    x = (content.find('nauu652pc41.dll'))
    if x > -1: detection += '@' + ('BumbleBee')
    if x > -1: Score = Score + 4
    return {"Score":Score,Score:detection}

def fscan(file):
    logging.basicConfig(filename='Inquisitor.log', filemode='a', format='%(name)s %(levelname)s %(asctime)s - %(message)s', level=logging.INFO)
    try:
        fileContent = open(file, 'r', encoding="ISO-8859-1").read()
        logging.info(f'┍{file}')

        scan = cscan(fileContent)
        Score = scan["Score"]
        Detection = '\n'.join(scan[Score].split('@'))

        if Score > 44:
            logging.critical(f'Detection: {Detection}')
            logging.critical(f'Score: {Score}')
            Cost = round(Score/10,2)
            logging.critical(f'Cost: {Cost}, EGP')
            return True, malicious.Critical, scan
        if Score < 44 and Score >= 16:
            logging.warning(f'Detection: {Detection}')
            logging.warning(f'Score: {Score}')
            Cost = round(Score/12,2)
            logging.info(f'Cost: {Cost} EGP')
            return True, malicious.NonCritical, scan
        logging.info(f'Detection: {Detection}')
        logging.warning(f'Score: {Score}')
        Cost = round(Score/21,2)
        logging.info(f'Cost: {Cost} EGP')
        return False, safe, scan
    except PermissionError:
        if _Choice("Do you want to Change the read access?"):
            print(f"Changing {file}'s Read Access.")
            os.chmod(file, stat.S_IROTH)
            return fscan(file)
        pass

if __name__ == '__main__':
    import sys
    if os.path.isdir(''.join(sys.argv[1:])):
        for root, dirs, files in os.walk(''.join(sys.argv[1:]), topdown=True):
            for i in files:
                if os.path.isfile(os.path.join(root,i)):
                    x = f"{os.path.join(root,i)}*{fscan(os.path.join(root,i))}"
                    try:
                        open('01I1', 'a').write(str(x))
                        print(x)
                    except PermissionError: pass
